// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnYj-iQMvIObA-7Ku9ppOw_y3Dy5tsfZo',
    appId: '1:944405370243:web:c97b5d460a3aad018ed2b6',
    messagingSenderId: '944405370243',
    projectId: 'profin-a4420',
    authDomain: 'profin-a4420.firebaseapp.com',
    storageBucket: 'profin-a4420.firebasestorage.app',
    measurementId: 'G-JBVJ11NKJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2Yu2SpxFLehEFfZFsEamyz4etCcrxCk',
    appId: '1:944405370243:android:70e3635b5d7150e48ed2b6',
    messagingSenderId: '944405370243',
    projectId: 'profin-a4420',
    storageBucket: 'profin-a4420.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkk4VH9HZjXjVAabCVTV0zxUsi8Jvpl9s',
    appId: '1:944405370243:ios:3928f84d0cc94cff8ed2b6',
    messagingSenderId: '944405370243',
    projectId: 'profin-a4420',
    storageBucket: 'profin-a4420.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkk4VH9HZjXjVAabCVTV0zxUsi8Jvpl9s',
    appId: '1:944405370243:ios:3928f84d0cc94cff8ed2b6',
    messagingSenderId: '944405370243',
    projectId: 'profin-a4420',
    storageBucket: 'profin-a4420.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnYj-iQMvIObA-7Ku9ppOw_y3Dy5tsfZo',
    appId: '1:944405370243:web:aca5d5f15b4096ac8ed2b6',
    messagingSenderId: '944405370243',
    projectId: 'profin-a4420',
    authDomain: 'profin-a4420.firebaseapp.com',
    storageBucket: 'profin-a4420.firebasestorage.app',
    measurementId: 'G-LDPNXRJHV9',
  );
}
